package com.horse.jk_bms.model

data class BmsConfig(
    val volSmartSleep: Float = 0f,
    val volCellUV: Float = 0f,
    val volCellUVPR: Float = 0f,
    val volCellOV: Float = 0f,
    val volCellOVPR: Float = 0f,
    val volBalanTrig: Float = 0f,
    val volSOCP100: Float = 0f,
    val volSOCP0: Float = 0f,
    val volCellRCV: Float = 0f,
    val volCellRFV: Float = 0f,
    val volSysPwrOff: Float = 0f,
    val timBatCOC: Float = 0f,
    val timBatCOCPDly: Long = 0,
    val timBatCOCPRDly: Long = 0,
    val timBatDcOC: Float = 0f,
    val timBatDcOCPDly: Long = 0,
    val timBatDcOCPRDly: Long = 0,
    val timBatSCPRDly: Long = 0,
    val curBalanMax: Float = 0f,
    val tmpBatCOT: Float = 0f,
    val tmpBatCOTPR: Float = 0f,
    val tmpBatDcOT: Float = 0f,
    val tmpBatDcOTPR: Float = 0f,
    val tmpBatCUT: Float = 0f,
    val tmpBatCUTPR: Float = 0f,
    val tmpMosOT: Float = 0f,
    val tmpMosOTPR: Float = 0f,
    val cellCount: Long = 0,
    val batChargeEn: Long = 0,
    val batDischargeEn: Long = 0,
    val balanEn: Long = 0,
    val capBatCell: Float = 0f,
    val scpDelay: Long = 0,
    val volStartBalan: Float = 0f,
    val cellConWireRes: FloatArray = FloatArray(32),
    val devAddr: Long = 0,
    val dischrgPreChrgT: Long = 0,
    val currentRange: Float = 0f,
    val switchStatus: BooleanArray = BooleanArray(16),
    val tmpStartHeating: Int = 0,
    val tmpStopHeating: Int = 0,
    val timeSmartSleep: Int = 0,
    val enableFlags: ByteArray = ByteArray(9),
    val tmpBatDCHUT: Int = 0,
    val tmpBatDCHUTPR: Int = 0,
) {
    override fun equals(other: Any?): Boolean = this === other
    override fun hashCode(): Int = System.identityHashCode(this)
}
