package com.horse.jk_bms.model

data class BmsDeviceInfo(
    val manuDeviceID: String = "",
    val maxCells: Int = 0,
    val hardwareVersion: String = "",
    val softwareVersion: String = "",
    val oddRunTime: Long = 0,
    val pwrOnTimes: Long = 0,
    val bluetoothName: String = "",
    val bluetoothPwd: String = "",
    val manufactureDate: String = "",
    val deviceSN: String = "",
    val userData: String = "",
    val settingPassword: String = "",
    val userData2: String = "",
    val cmdSupportFlags: ByteArray = ByteArray(32),
    val agencyId: Int = 0,
    val uart1ProtoNo: Int = 0,
    val canProtoNo: Int = 0,
    val uart1ProtoEnabled: ByteArray = ByteArray(4),
    val hardwareOption: String = "",
    val canProtoEnabled: ByteArray = ByteArray(4),
    val uart2ProtoNo: Int = 0,
    val uart2ProtoEnabled: ByteArray = ByteArray(4),
    val lcdBuzzerTrigger: Int = 0,
    val dry1Trigger: Int = 0,
    val dry2Trigger: Int = 0,
    val uartMPTLVer: Int = 0,
    val lcdBuzzerTriggerVal: Int = 0,
    val lcdBuzzerReleaseVal: Int = 0,
    val dry1TriggerVal: Int = 0,
    val dry1ReleaseVal: Int = 0,
    val dry2TriggerVal: Int = 0,
    val dry2ReleaseVal: Int = 0,
    val dataStoredPeriod: Long = 0,
    val rcvTime: Float = 0f,
    val rfvTime: Float = 0f,
    val canMPTLVer: Int = 0,
    val emergencyTime: Int = 0,
    val uart3ProtoNo: Int = 0,
    val uart3ProtoEnabled: ByteArray = ByteArray(7),
    val reBulkSOC: Int = 0,
    val enableFlags: ByteArray = ByteArray(11),
    val protocolVer: Int = 0,
) {
    override fun equals(other: Any?): Boolean = this === other
    override fun hashCode(): Int = System.identityHashCode(this)
}
